export type PartCategory =
  | "Cockpit"
  | "Hab"
  | "Walkway"
  | "Aerofoil"
  | "Wing"
  | "Cowling"
  | "Diffuser"
  | "Dome"
  | "Nacelle"
  | "Casing"
  | "Trim"
  | "Sidepod"
  | "Fin"
  | "Thruster"
  | "Landing Bay"
  | "Landing Gear"
  | "Weapon Mount"
  | "Shielding"
  | "Reactor";

export interface PartDefinition {
  id: string;
  name: string;
  category: PartCategory;
  /** Maximum number of times this module can be built */
  maxCount: number;
  /** Optional shared pool key for variant-exclusive part limits */
  countGroup?: string;
  /** Width in grid cells */
  w: number;
  /** Height in grid cells */
  h: number;
  color: string;
  description: string;
}

export const GRID_COLS = 10;
export const GRID_ROWS = 6;
export const GRID_LAYERS = 6;

export const PARTS: PartDefinition[] = [
  // Cockpit
  {
    id: "titan-class-cockpit",
    name: "Titan-Class Cockpit",
    category: "Cockpit",
    maxCount: 1,
    countGroup: "cockpit",
    w: 2,
    h: 1,
    color: "#f59e0b",
    description: "Heavy Titan-series command cockpit module.",
  },
  {
    id: "ambassador-class-cockpit",
    name: "Ambassador-Class Cockpit",
    category: "Cockpit",
    maxCount: 1,
    countGroup: "cockpit",
    w: 2,
    h: 1,
    color: "#d97706",
    description: "Balanced Ambassador-series command cockpit module.",
  },
  {
    id: "thunderbird-class-cockpit",
    name: "Thunderbird-Class Cockpit",
    category: "Cockpit",
    maxCount: 1,
    countGroup: "cockpit",
    w: 2,
    h: 1,
    color: "#b45309",
    description: "Compact Thunderbird-series command cockpit module.",
  },
  // Hab
  {
    id: "titan-class-hab",
    name: "Titan-Class Hab",
    category: "Hab",
    maxCount: 3,
    w: 2,
    h: 1,
    color: "#0ea5e9",
    description: "Titan-series habitation bay segment.",
  },
  {
    id: "ambassador-class-hab",
    name: "Ambassador-Class Hab",
    category: "Hab",
    maxCount: 3,
    w: 2,
    h: 1,
    color: "#0284c7",
    description: "Ambassador-series habitation bay segment.",
  },
  {
    id: "thunderbird-class-hab",
    name: "Thunderbird-Class Hab",
    category: "Hab",
    maxCount: 3,
    w: 2,
    h: 1,
    color: "#0369a1",
    description: "Thunderbird-series habitation bay segment.",
  },
  // Walkway
  {
    id: "titan-class-walkway",
    name: "Titan-Class Walkway",
    category: "Walkway",
    maxCount: 4,
    w: 1,
    h: 2,
    color: "#64748b",
    description: "Titan-series internal connector walkway.",
  },
  {
    id: "ambassador-class-walkway",
    name: "Ambassador-Class Walkway",
    category: "Walkway",
    maxCount: 4,
    w: 1,
    h: 2,
    color: "#475569",
    description: "Ambassador-series internal connector walkway.",
  },
  {
    id: "thunderbird-class-walkway",
    name: "Thunderbird-Class Walkway",
    category: "Walkway",
    maxCount: 4,
    w: 1,
    h: 2,
    color: "#334155",
    description: "Thunderbird-series internal connector walkway.",
  },
  // Aerofoil
  {
    id: "supercruise-aerofoil",
    name: "Supercruise Aerofoil",
    category: "Aerofoil",
    maxCount: 4,
    w: 2,
    h: 1,
    color: "#22c55e",
    description: "Supercruise-pattern aerofoil hull panel.",
  },
  {
    id: "arcadia-aerofoil",
    name: "Arcadia Aerofoil",
    category: "Aerofoil",
    maxCount: 4,
    w: 2,
    h: 1,
    color: "#16a34a",
    description: "Arcadia-pattern aerofoil hull panel.",
  },
  {
    id: "argonaut-aerofoil",
    name: "Argonaut Aerofoil",
    category: "Aerofoil",
    maxCount: 4,
    w: 2,
    h: 1,
    color: "#15803d",
    description: "Argonaut-pattern aerofoil hull panel.",
  },
  {
    id: "arcadia-s-foil",
    name: "Arcadia S-Foil",
    category: "Aerofoil",
    maxCount: 4,
    w: 2,
    h: 1,
    color: "#166534",
    description: "Arcadia S-profile aerofoil wing plate.",
  },
  // Wing
  {
    id: "titan-wing-module",
    name: "Titan Wing Module",
    category: "Wing",
    maxCount: 4,
    w: 2,
    h: 1,
    color: "#3b82f6",
    description: "Titan-series lateral wing assembly.",
  },
  {
    id: "ambassador-wing-module",
    name: "Ambassador Wing Module",
    category: "Wing",
    maxCount: 4,
    w: 2,
    h: 1,
    color: "#2563eb",
    description: "Ambassador-series lateral wing assembly.",
  },
  {
    id: "osprey-wing-module",
    name: "Osprey Wing Module",
    category: "Wing",
    maxCount: 4,
    w: 2,
    h: 1,
    color: "#1d4ed8",
    description: "Osprey-series lateral wing assembly.",
  },
  {
    id: "rockhopper-wing-module",
    name: "Rockhopper Wing Module",
    category: "Wing",
    maxCount: 4,
    w: 2,
    h: 1,
    color: "#1e40af",
    description: "Rockhopper-series lateral wing assembly.",
  },
  {
    id: "rockhopper-propeller-module",
    name: "Rockhopper Propeller Module",
    category: "Wing",
    maxCount: 2,
    w: 1,
    h: 2,
    color: "#1e3a8a",
    description: "Rockhopper propeller-style wing extension.",
  },
  // Cowling
  {
    id: "supercruise-cowling",
    name: "Supercruise Cowling",
    category: "Cowling",
    maxCount: 4,
    w: 2,
    h: 1,
    color: "#0891b2",
    description: "Supercruise hull cowling panel.",
  },
  {
    id: "speedbird-cowling",
    name: "Speedbird Cowling",
    category: "Cowling",
    maxCount: 4,
    w: 2,
    h: 1,
    color: "#0e7490",
    description: "Speedbird forward cowling shell segment.",
  },
  {
    id: "vesper-cowling",
    name: "Vesper Cowling",
    category: "Cowling",
    maxCount: 4,
    w: 2,
    h: 1,
    color: "#155e75",
    description: "Vesper forward cowling shell segment.",
  },
  {
    id: "firebox-cowling",
    name: "Firebox Cowling",
    category: "Cowling",
    maxCount: 4,
    w: 2,
    h: 1,
    color: "#164e63",
    description: "Firebox-series armoured cowling shell.",
  },
  {
    id: "speedbird-fairing",
    name: "Speedbird Fairing",
    category: "Cowling",
    maxCount: 3,
    w: 2,
    h: 1,
    color: "#134e4a",
    description: "Speedbird fairing shell connector.",
  },
  {
    id: "firebox-fairing",
    name: "Firebox Fairing",
    category: "Cowling",
    maxCount: 3,
    w: 2,
    h: 1,
    color: "#0f766e",
    description: "Firebox fairing shell connector.",
  },
  // Diffuser
  {
    id: "speedbird-diffuser",
    name: "Speedbird Diffuser",
    category: "Diffuser",
    maxCount: 3,
    w: 2,
    h: 1,
    color: "#7c2d12",
    description: "Speedbird rear exhaust diffuser panel.",
  },
  {
    id: "vesper-diffuser",
    name: "Vesper Diffuser",
    category: "Diffuser",
    maxCount: 3,
    w: 2,
    h: 1,
    color: "#9a3412",
    description: "Vesper rear exhaust diffuser panel.",
  },
  {
    id: "vesper-diffuser-rim",
    name: "Vesper Diffuser Rim",
    category: "Diffuser",
    maxCount: 3,
    w: 1,
    h: 1,
    color: "#c2410c",
    description: "Rim connector for Vesper diffuser housing.",
  },
  // Dome
  {
    id: "speedbird-dome-rim",
    name: "Speedbird Dome Rim",
    category: "Dome",
    maxCount: 2,
    w: 2,
    h: 1,
    color: "#7e22ce",
    description: "Rim frame for Speedbird dome section.",
  },
  {
    id: "speedbird-dome-section",
    name: "Speedbird Dome Section",
    category: "Dome",
    maxCount: 2,
    w: 2,
    h: 1,
    color: "#6b21a8",
    description: "Primary canopy dome hull section.",
  },
  // Nacelle
  {
    id: "speedbird-nacelle",
    name: "Speedbird Nacelle",
    category: "Nacelle",
    maxCount: 2,
    w: 1,
    h: 2,
    color: "#be123c",
    description: "Speedbird engine nacelle structure.",
  },
  {
    id: "speedbird-nacelle-rim",
    name: "Speedbird Nacelle Rim",
    category: "Nacelle",
    maxCount: 2,
    w: 1,
    h: 1,
    color: "#9f1239",
    description: "Rim panel for Speedbird nacelle joint.",
  },
  // Casing
  {
    id: "domed-casing",
    name: "Domed Casing",
    category: "Casing",
    maxCount: 3,
    w: 2,
    h: 1,
    color: "#4d7c0f",
    description: "Domed external casing hull segment.",
  },
  {
    id: "domed-casing-cap",
    name: "Domed Casing Cap",
    category: "Casing",
    maxCount: 3,
    w: 1,
    h: 1,
    color: "#3f6212",
    description: "Cap connector for domed casing ends.",
  },
  {
    id: "radiator-casing",
    name: "Radiator Casing",
    category: "Casing",
    maxCount: 3,
    w: 2,
    h: 1,
    color: "#365314",
    description: "Heat-radiator casing segment.",
  },
  {
    id: "swept-casing",
    name: "Swept Casing",
    category: "Casing",
    maxCount: 3,
    w: 2,
    h: 1,
    color: "#166534",
    description: "Swept-profile external casing segment.",
  },
  {
    id: "swept-casing-cap",
    name: "Swept Casing Cap",
    category: "Casing",
    maxCount: 3,
    w: 1,
    h: 1,
    color: "#14532d",
    description: "Cap connector for swept casing ends.",
  },
  // Trim
  {
    id: "streamlined-trim",
    name: "Streamlined Trim",
    category: "Trim",
    maxCount: 6,
    w: 1,
    h: 1,
    color: "#374151",
    description: "Low-profile trim strip for hull seams.",
  },
  {
    id: "streamlined-trim-cap",
    name: "Streamlined Trim Cap",
    category: "Trim",
    maxCount: 6,
    w: 1,
    h: 1,
    color: "#1f2937",
    description: "End-cap for streamlined trim sections.",
  },
  {
    id: "engine-cover",
    name: "Engine Cover",
    category: "Trim",
    maxCount: 4,
    w: 2,
    h: 1,
    color: "#111827",
    description: "Protective shell for rear engine segment.",
  },
  {
    id: "engine-cover-rim",
    name: "Engine Cover Rim",
    category: "Trim",
    maxCount: 4,
    w: 1,
    h: 1,
    color: "#030712",
    description: "Rim piece for engine cover joint.",
  },
  // Sidepod
  {
    id: "albatross-sidepod",
    name: "Albatross Sidepod",
    category: "Sidepod",
    maxCount: 4,
    w: 1,
    h: 2,
    color: "#0f172a",
    description: "Albatross-series sidepod extension.",
  },
  {
    id: "firebox-sidepod-cap",
    name: "Firebox Sidepod Cap",
    category: "Sidepod",
    maxCount: 4,
    w: 1,
    h: 1,
    color: "#1e293b",
    description: "Cap connector for Firebox sidepod section.",
  },
  // Fin
  {
    id: "rockhopper-fin-module",
    name: "Rockhopper Fin Module",
    category: "Fin",
    maxCount: 3,
    w: 1,
    h: 2,
    color: "#6d28d9",
    description: "Rockhopper dorsal fin hull segment.",
  },
  // Thruster
  {
    id: "titan-heavy-booster",
    name: "Titan Heavy Booster",
    category: "Thruster",
    maxCount: 2,
    w: 1,
    h: 2,
    color: "#ef4444",
    description: "Titan-series heavy booster thruster housing.",
  },
  {
    id: "titan-sublight-thruster",
    name: "Titan Sublight Thruster",
    category: "Thruster",
    maxCount: 2,
    w: 1,
    h: 2,
    color: "#dc2626",
    description: "Titan-series sublight propulsion nozzle.",
  },
  {
    id: "ambassador-heavy-booster",
    name: "Ambassador Heavy Booster",
    category: "Thruster",
    maxCount: 2,
    w: 1,
    h: 2,
    color: "#b91c1c",
    description: "Ambassador-series heavy booster thruster housing.",
  },
  {
    id: "thunderbird-heavy-booster",
    name: "Thunderbird Heavy Booster",
    category: "Thruster",
    maxCount: 2,
    w: 1,
    h: 2,
    color: "#991b1b",
    description: "Thunderbird-series heavy booster thruster housing.",
  },
  // Landing Bay
  {
    id: "titan-class-landing-bay",
    name: "Titan-Class Landing Bay",
    category: "Landing Bay",
    maxCount: 2,
    countGroup: "landing-bay",
    w: 2,
    h: 2,
    color: "#8b5cf6",
    description: "Titan-series landing and docking bay section.",
  },
  {
    id: "ambassador-class-landing-bay",
    name: "Ambassador-Class Landing Bay",
    category: "Landing Bay",
    maxCount: 2,
    countGroup: "landing-bay",
    w: 2,
    h: 2,
    color: "#7c3aed",
    description: "Ambassador-series landing and docking bay section.",
  },
  {
    id: "thunderbird-class-landing-bay",
    name: "Thunderbird-Class Landing Bay",
    category: "Landing Bay",
    maxCount: 2,
    countGroup: "landing-bay",
    w: 2,
    h: 2,
    color: "#6d28d9",
    description: "Thunderbird-series landing and docking bay section.",
  },
  // Landing Gear
  {
    id: "hydraulic-legs",
    name: "Hydraulic Legs",
    category: "Landing Gear",
    maxCount: 4,
    w: 1,
    h: 2,
    color: "#a16207",
    description: "Hydraulic support struts for landing assemblies.",
  },
  {
    id: "landing-gear",
    name: "Landing Gear",
    category: "Landing Gear",
    maxCount: 4,
    w: 1,
    h: 2,
    color: "#854d0e",
    description: "Primary landing gear support module.",
  },
  {
    id: "mag-field-landing-thrusters",
    name: "Mag-Field Landing Thrusters",
    category: "Landing Gear",
    maxCount: 4,
    w: 1,
    h: 1,
    color: "#713f12",
    description: "Magnetic field assisted landing thruster node.",
  },
  // Weapon Mount
  {
    id: "cyclotron-defence-cannon",
    name: "Cyclotron Defence Cannon",
    category: "Weapon Mount",
    maxCount: 3,
    w: 1,
    h: 1,
    color: "#ef4444",
    description: "Integrated point-defence cannon emplacement.",
  },
  {
    id: "phase-beam-array",
    name: "Phase Beam Array",
    category: "Weapon Mount",
    maxCount: 3,
    w: 1,
    h: 1,
    color: "#f97316",
    description: "Arrayed beam weapon hardpoint.",
  },
  {
    id: "photon-cannon-array",
    name: "Photon Cannon Array",
    category: "Weapon Mount",
    maxCount: 3,
    w: 1,
    h: 1,
    color: "#fb7185",
    description: "Arrayed photon cannon hardpoint.",
  },
  {
    id: "torpedo-launcher",
    name: "Torpedo Launcher",
    category: "Weapon Mount",
    maxCount: 2,
    w: 1,
    h: 2,
    color: "#be123c",
    description: "Heavy torpedo launch tube assembly.",
  },
  // Shielding
  {
    id: "defence-field",
    name: "Defence Field",
    category: "Shielding",
    maxCount: 2,
    w: 1,
    h: 1,
    color: "#38bdf8",
    description: "Projected defensive field node.",
  },
  {
    id: "deflector-shield",
    name: "Deflector Shield",
    category: "Shielding",
    maxCount: 2,
    w: 1,
    h: 1,
    color: "#0ea5e9",
    description: "Deflector shield emitter assembly.",
  },
  {
    id: "high-energy-shield",
    name: "High-Energy Shield",
    category: "Shielding",
    maxCount: 2,
    w: 1,
    h: 1,
    color: "#0284c7",
    description: "High-output shield emitter assembly.",
  },
  {
    id: "ion-barrier",
    name: "Ion Barrier",
    category: "Shielding",
    maxCount: 2,
    w: 1,
    h: 1,
    color: "#0369a1",
    description: "Ionized barrier shield node.",
  },
  // Reactor
  {
    id: "zenith-class-reactor",
    name: "Zenith-Class Reactor",
    category: "Reactor",
    maxCount: 1,
    countGroup: "reactor",
    w: 2,
    h: 1,
    color: "#14b8a6",
    description: "Zenith-class reactor core section.",
  },
  {
    id: "medusa-class-reactor",
    name: "Medusa-Class Reactor",
    category: "Reactor",
    maxCount: 1,
    countGroup: "reactor",
    w: 2,
    h: 1,
    color: "#0d9488",
    description: "Medusa-class reactor core section.",
  },
  {
    id: "azimuth-class-reactor",
    name: "Azimuth-Class Reactor",
    category: "Reactor",
    maxCount: 1,
    countGroup: "reactor",
    w: 2,
    h: 1,
    color: "#0f766e",
    description: "Azimuth-class reactor core section.",
  },
  {
    id: "ceto-class-reactor",
    name: "Ceto-Class Reactor",
    category: "Reactor",
    maxCount: 1,
    countGroup: "reactor",
    w: 2,
    h: 1,
    color: "#115e59",
    description: "Ceto-class reactor core section.",
  },
];

export type Rotation = 0 | 90 | 180 | 270;

export interface PlacedPart {
  instanceId: string;
  partId: string;
  col: number;
  row: number;
  /** Vertical layer (0 = bottom, GRID_LAYERS-1 = top) */
  layer: number;
  rotation: Rotation;
}
